"""Versioned procedures for deterministic and model-assisted Harness X operation."""

from .assisted import (
    AssistedDecisionOutcome,
    AssistedDecisionRequest,
    DecisionEvaluation,
    DecisionFamily,
    ExperimentProposalRoutine,
    HypothesisProposalRoutine,
    PlanningProposalRoutine,
    RecommendationSource,
    RecoveryProposalRoutine,
    RetrievalQueryRoutine,
    RoutineSelectionProposalRoutine,
    SemanticCandidateProposalRoutine,
    deterministic_baseline,
    evaluate_payload,
    register_model_assisted_routines,
)
from .base import (
    RoutineBindings,
    RoutineError,
    RoutineExecution,
    RoutineResult,
    RoutineSpec,
    RoutineStatus,
    ScriptedRoutine,
    routine_request_fingerprint,
)
from .engine import RoutineEngine
from .scripted import (
    ConsolidationRoutine,
    ConsolidationRoutineRequest,
    ConsolidationSummary,
    RecoveryRoutine,
    RecoveryRoutineRequest,
    ScriptedReasoningStub,
    TaskRoutine,
    TaskRoutineRequest,
    VerificationRoutine,
    VerificationRoutineRequest,
    build_scripted_routine_engine,
)
from .tool_task import (
    ToolAwareScriptedReasoningStub,
    ToolTaskRoutine,
    ToolTaskRoutineRequest,
    build_tool_routine_engine,
)

__all__ = [
    "AssistedDecisionOutcome",
    "AssistedDecisionRequest",
    "ConsolidationRoutine",
    "ConsolidationRoutineRequest",
    "ConsolidationSummary",
    "DecisionEvaluation",
    "DecisionFamily",
    "ExperimentProposalRoutine",
    "HypothesisProposalRoutine",
    "PlanningProposalRoutine",
    "RecommendationSource",
    "RecoveryProposalRoutine",
    "RecoveryRoutine",
    "RecoveryRoutineRequest",
    "RetrievalQueryRoutine",
    "RoutineBindings",
    "RoutineEngine",
    "RoutineError",
    "RoutineExecution",
    "RoutineResult",
    "RoutineSelectionProposalRoutine",
    "RoutineSpec",
    "RoutineStatus",
    "ScriptedReasoningStub",
    "ScriptedRoutine",
    "SemanticCandidateProposalRoutine",
    "TaskRoutine",
    "TaskRoutineRequest",
    "ToolAwareScriptedReasoningStub",
    "ToolTaskRoutine",
    "ToolTaskRoutineRequest",
    "VerificationRoutine",
    "VerificationRoutineRequest",
    "build_scripted_routine_engine",
    "build_tool_routine_engine",
    "deterministic_baseline",
    "evaluate_payload",
    "register_model_assisted_routines",
    "routine_request_fingerprint",
]
