"""Replaceable reasoning cores behind a software-owned normalization boundary."""

from .base import (
    RawActionProposal,
    RawProposal,
    RawReasoningOutput,
    ReasoningCore,
    ReasoningCoreError,
    ReasoningCoreInfo,
)
from .context_builder import BoundedContextBuilder, ContextBudget, ContextBuildResult
from .profiles import (
    ModelCapability,
    ModelProfile,
    ModelProfileBackend,
    ModelProfileRegistry,
    ModelProfileRole,
    ModelProvider,
    builtin_model_profiles,
    load_model_profile_registry,
    model_profile_registry,
    model_profile_registry_json,
)
from .service import ReasoningService
from .stub import StubReasoningCore
from .adapters import (
    OpenAICompatibleConnectionResult,
    OpenAICompatibleReasoningCore,
    OpenAICompatibleSettings,
    TransformersLocalReasoningCore,
    TransformersLocalSettings,
)
from .recurrent_depth import (
    DEFAULT_DEPTHS,
    DEPTH_SELECTOR_VERSION,
    RECURRENT_DEPTH_RESEARCH_VERSION,
    DepthSelectionState,
    DepthSelectorArtifact,
    DepthSelectorComparison,
    DeterministicDepthSelector,
    FixedDepthCurveReport,
    FixedDepthRecurrentCore,
    HuginnTransformersBackend,
    HuginnTransformersSettings,
    LearnedDepthSelector,
    RecurrentDepthAuthority,
    RecurrentDepthAuthorization,
    RecurrentDepthBackend,
    RecurrentDepthBenchmarkCase,
    RecurrentDepthResearchError,
    RecurrentDepthResearchReport,
    benchmark_fixed_depth_curve,
    build_reference_recurrent_depth_fixture,
    load_recurrent_depth_cases,
    prepare_depth_selection_examples,
    run_recurrent_depth_research,
    run_reference_recurrent_depth_research,
)

__all__ = [
    "BoundedContextBuilder",
    "ContextBudget",
    "ContextBuildResult",
    "DEFAULT_DEPTHS",
    "DEPTH_SELECTOR_VERSION",
    "DepthSelectionState",
    "DepthSelectorArtifact",
    "DepthSelectorComparison",
    "DeterministicDepthSelector",
    "FixedDepthCurveReport",
    "FixedDepthRecurrentCore",
    "HuginnTransformersBackend",
    "HuginnTransformersSettings",
    "LearnedDepthSelector",
    "ModelCapability",
    "ModelProfile",
    "ModelProfileBackend",
    "ModelProfileRegistry",
    "ModelProfileRole",
    "ModelProvider",
    "OpenAICompatibleConnectionResult",
    "OpenAICompatibleReasoningCore",
    "OpenAICompatibleSettings",
    "RECURRENT_DEPTH_RESEARCH_VERSION",
    "RawActionProposal",
    "RawProposal",
    "RawReasoningOutput",
    "ReasoningCore",
    "ReasoningCoreError",
    "ReasoningCoreInfo",
    "ReasoningService",
    "RecurrentDepthAuthority",
    "RecurrentDepthAuthorization",
    "RecurrentDepthBackend",
    "RecurrentDepthBenchmarkCase",
    "RecurrentDepthResearchError",
    "RecurrentDepthResearchReport",
    "StubReasoningCore",
    "TransformersLocalReasoningCore",
    "TransformersLocalSettings",
    "benchmark_fixed_depth_curve",
    "build_reference_recurrent_depth_fixture",
    "builtin_model_profiles",
    "load_model_profile_registry",
    "load_recurrent_depth_cases",
    "model_profile_registry",
    "model_profile_registry_json",
    "prepare_depth_selection_examples",
    "run_recurrent_depth_research",
    "run_reference_recurrent_depth_research",
]
