"""Coding-task runtime for Harness X."""

from .autonomous_runtime import AutonomousCodingTaskRuntime
from .browser_runtime import (
    BrowserContextReasoningCore,
    BrowserVerifiedCodingTaskReport,
    BrowserVerifiedIsolatedCodingTaskReport,
    BrowserVerifiedIsolatedRepositoryCodingTaskRuntime,
    BrowserVerifiedRepositoryCodingTaskRuntime,
)
from .browser_verification import (
    BrowserConsoleVerificationCheck,
    BrowserInteractionAction,
    BrowserInteractionVerificationCheck,
    BrowserPageVerificationCheck,
    BrowserVerificationPlan,
    BrowserVerificationPlatform,
    BrowserVerificationResult,
    BrowserVerificationRun,
    load_browser_verification_plan,
)
from .isolated_runtime import (
    IsolatedCodingTaskReport,
    IsolatedRepositoryCodingTaskRuntime,
)
from .isolation import (
    IsolationResult,
    IsolationRetention,
    IsolationStrategy,
    SourceWorkspaceIdentity,
    TaskWorkspaceChange,
    TaskWorkspaceIsolationManager,
)
from .procedure_improvement_browser_campaign import ProcedureImprovementBrowserCampaignRunner
from .procedure_improvement_campaign import (
    PendingProcedureImprovementStep,
    ProcedureImprovementCampaign,
    ProcedureImprovementCampaignBudget,
    ProcedureImprovementCampaignReport,
    ProcedureImprovementCampaignRunner,
    ProcedureImprovementCampaignStatus,
    ProcedureImprovementCampaignStepReport,
    ProcedureImprovementCampaignStore,
    ProcedureImprovementCampaignStoreState,
    ProcedureImprovementStepKind,
)
from .procedure_revision import (
    ProcedureRevisionCandidate,
    ProcedureRevisionPolicy,
    ProcedureRevisionProposal,
    ProcedureRevisionState,
    ProcedureRevisionStore,
    ProcedureRevisionUpdateProposal,
)
from .procedure_revision_runtime import (
    ProcedureRevisionBrowserCodingTaskReport,
    ProcedureRevisionBrowserIsolatedCodingTaskReport,
    ProcedureRevisionBrowserIsolatedRepositoryCodingTaskRuntime,
    ProcedureRevisionBrowserRepositoryCodingTaskRuntime,
    ProcedureRevisionCodingTaskReport,
    ProcedureRevisionContextReasoningCore,
    ProcedureRevisionIsolatedCodingTaskReport,
    ProcedureRevisionIsolatedRepositoryCodingTaskRuntime,
    ProcedureRevisionVerifiedRepositoryCodingTaskRuntime,
    RevisionAwareProjectMemoryStore,
)
from .profile_comparison import (
    ComparableRunSummary,
    ProfileRunComparisonReport,
    ProfileRunMetricDeltas,
    compare_profile_run_roots,
    load_comparable_run,
    write_profile_run_comparison,
)
from .repository_runtime import (
    RepositoryAwareAutonomousCodingTaskRuntime,
    RepositoryContextReasoningCore,
)
from .run_manifest import (
    CodingRunManifest,
    build_coding_run_manifest,
    clone_comparison_memory_seed,
    directory_fingerprint,
    load_coding_run_manifest,
    write_coding_run_manifest,
)
from .runtime import CodingTaskReport, CodingTaskRuntime, CodingVerificationResult
from .strict_verification import StrictVerificationPlatform
from .verification import (
    CommandVerificationCheck,
    FileContainsVerificationCheck,
    FileExistsVerificationCheck,
    VerificationCheckResult,
    VerificationCheckStatus,
    VerificationPlan,
    VerificationPlatform,
    VerificationRequirement,
    VerificationRun,
    VerificationVerdict,
    command_verification_plan,
    load_verification_plan,
)
from .verified_runtime import (
    VerificationContextReasoningCore,
    VerifiedCodingTaskReport,
    VerifiedIsolatedCodingTaskReport,
    VerifiedIsolatedRepositoryCodingTaskRuntime,
    VerifiedRepositoryCodingTaskRuntime,
)

__all__ = [
    "AutonomousCodingTaskRuntime",
    "BrowserConsoleVerificationCheck",
    "BrowserContextReasoningCore",
    "BrowserInteractionAction",
    "BrowserInteractionVerificationCheck",
    "BrowserPageVerificationCheck",
    "BrowserVerificationPlan",
    "BrowserVerificationPlatform",
    "BrowserVerificationResult",
    "BrowserVerificationRun",
    "BrowserVerifiedCodingTaskReport",
    "BrowserVerifiedIsolatedCodingTaskReport",
    "BrowserVerifiedIsolatedRepositoryCodingTaskRuntime",
    "BrowserVerifiedRepositoryCodingTaskRuntime",
    "CodingRunManifest",
    "CodingTaskReport",
    "CodingTaskRuntime",
    "CodingVerificationResult",
    "CommandVerificationCheck",
    "ComparableRunSummary",
    "FileContainsVerificationCheck",
    "FileExistsVerificationCheck",
    "IsolatedCodingTaskReport",
    "IsolatedRepositoryCodingTaskRuntime",
    "IsolationResult",
    "IsolationRetention",
    "IsolationStrategy",
    "PendingProcedureImprovementStep",
    "ProcedureImprovementBrowserCampaignRunner",
    "ProcedureImprovementCampaign",
    "ProcedureImprovementCampaignBudget",
    "ProcedureImprovementCampaignReport",
    "ProcedureImprovementCampaignRunner",
    "ProcedureImprovementCampaignStatus",
    "ProcedureImprovementCampaignStepReport",
    "ProcedureImprovementCampaignStore",
    "ProcedureImprovementCampaignStoreState",
    "ProcedureImprovementStepKind",
    "ProcedureRevisionBrowserCodingTaskReport",
    "ProcedureRevisionBrowserIsolatedCodingTaskReport",
    "ProcedureRevisionBrowserIsolatedRepositoryCodingTaskRuntime",
    "ProcedureRevisionBrowserRepositoryCodingTaskRuntime",
    "ProcedureRevisionCandidate",
    "ProcedureRevisionCodingTaskReport",
    "ProcedureRevisionContextReasoningCore",
    "ProcedureRevisionIsolatedCodingTaskReport",
    "ProcedureRevisionIsolatedRepositoryCodingTaskRuntime",
    "ProcedureRevisionPolicy",
    "ProcedureRevisionProposal",
    "ProcedureRevisionState",
    "ProcedureRevisionStore",
    "ProcedureRevisionUpdateProposal",
    "ProcedureRevisionVerifiedRepositoryCodingTaskRuntime",
    "ProfileRunComparisonReport",
    "ProfileRunMetricDeltas",
    "RepositoryAwareAutonomousCodingTaskRuntime",
    "RepositoryContextReasoningCore",
    "RevisionAwareProjectMemoryStore",
    "SourceWorkspaceIdentity",
    "StrictVerificationPlatform",
    "TaskWorkspaceChange",
    "TaskWorkspaceIsolationManager",
    "VerificationCheckResult",
    "VerificationCheckStatus",
    "VerificationContextReasoningCore",
    "VerificationPlan",
    "VerificationPlatform",
    "VerificationRequirement",
    "VerificationRun",
    "VerificationVerdict",
    "VerifiedCodingTaskReport",
    "VerifiedIsolatedCodingTaskReport",
    "VerifiedIsolatedRepositoryCodingTaskRuntime",
    "VerifiedRepositoryCodingTaskRuntime",
    "build_coding_run_manifest",
    "clone_comparison_memory_seed",
    "command_verification_plan",
    "compare_profile_run_roots",
    "directory_fingerprint",
    "load_browser_verification_plan",
    "load_coding_run_manifest",
    "load_comparable_run",
    "load_verification_plan",
    "write_coding_run_manifest",
    "write_profile_run_comparison",
]
